language: node_js

node_js:
  - "node"
  - "lts/*"
  - "7"

notifications:
  email: false

sudo: false

install:
  - npm install

cache:
  directories:
    - "node_modules"

script:
  - mocha ./05nodeTest/fibonacci.test
  - mocha ./07supertest

