language: node_js

node_js:
  - "node"
  - "lts/*"
  - "iojs"
  - "7"

notifications:
  email: false

sudo: false

before_install:
  - chmod +x gradlew

install:
  - npm install

cache:
  directories:
    - "node_modules"
